name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get external dependencies
        run: make edeps

      - name: Generate static files package
        run: make statik

      - name: Get other dependencies
        run: make deps

      - name: Build
        run: make

      - name: Test with coverage
        run: make testcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
